# Remove this if your site folder is not inside the theme folder
# themesDir = "../../"

theme = "hugo-tufte"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
defaultContentLang = "fr"
# The url of your website
baseurl = ""
title = "Arveed"
math = true
# (If math is enabled) 
## if "katex" is set to true katex will be used to render LaTex, if not MathJax will be used instead
katex = true

[params]
  subtitle = "Arveed est le site personnel du romancier Cyril Vallée."
  copyrightHolder = "Cyril Vallée"
  showPoweredBy = false
  hidedate = false
  # Uncomment for dark code blocks
  # codeBlocksDark = true

  # Common social website links, please comment the unused ones.
  github = "crlvll"
  # gitlab = "slashformotion"
  twitter = "_cyrilvallee_"
  # patreon = ""
  # youtube = "user/ChromeDevelopers" # check the end of your youtube url https://www.youtube.com/<copy_this>
  # medium = "slashformotion"
  # reddit = "Slashformotion"
  # stackoverflow = "16609732/slashformotion"
  instagram = "_cyrilvallee_"
  mastodon = "tooting.ch/@arveed"
  # orcid = "0000-0003-0634-3275"
  # google_scholar = "jm5QaHkAAAAJ"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
#[[menu.nav]]
#  name = "Accueil"
#  pre = "<i class='fas fa-home la-lg'></i>"
#  weight = -110 
#  identifier = "home"
#  url = "/"
#[[menu.nav]]
#  name = "Now"
#  pre = "<i class='fas fa-tags fa-lg'></i> "
#  weight = -90 
#  identifier = "categories"
#  url = "/now"
[[menu.nav]]
  name = "À propos"
  pre = ""
  weight = -80 
  identifier = "a-propos"
  url = "/a-propos"
[[menu.nav]]
  name = "Mes Livres"
  pre = ""
  weight = -70 
  identifier = "livres"
  url = "https://www.cyrilvallee.com"
#[[menu.nav]]
#  name = "Archives"
#  pre = ""
#  weight = -60 
#  identifier = "Les Archives"
#  url = "/articles"

# -----------------------------------------------------------------------
# FOOTER MENU
# If you need to add custom links to you footer: put them here. Be aware that this theme is using fontawesome. 
# Please head to https://fontawesome.com/v4.7/icons/ to pick icons
# -----------------------------------------------------------------------

##[[menu.footer]]
##  name = "Custom footer link"
##  pre = "<i class='fab fa-google fa-lg'></i> "
##  weight = -90 
##  identifier = "custom_link"
##  url = "https://google.com"


# Don't change the settings below
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # make the shortcodes work
  [markup.highlight]
      noClasses = false

pygmentsUseClasses = true
canonifyurls = true
